# Generated by Django 3.2.4 on 2021-06-13 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('page_no', models.IntegerField(default=1)),
                ('page_size', models.IntegerField(default=15)),
                ('from_date', models.CharField(max_length=20)),
                ('to_date', models.CharField(max_length=20)),
                ('order_by', models.CharField(choices=[('asc', 'asc'), ('desc', 'desc')], max_length=4)),
                ('min_date', models.CharField(max_length=20)),
                ('max_date', models.CharField(max_length=20)),
                ('sort_by', models.CharField(choices=[('activity', 'activity'), ('votes', 'votes'), ('creation', 'creation'), ('relevance', 'relevance')], max_length=10)),
                ('question', models.CharField(max_length=200)),
                ('is_accepted', models.BooleanField(null=True)),
                ('no_of_answers', models.CharField(max_length=20)),
                ('body', models.CharField(max_length=200)),
                ('is_closed', models.BooleanField(null=True)),
                ('is_migrated', models.BooleanField(null=True)),
                ('notice', models.BooleanField(null=True)),
                ('not_tagged', models.CharField(max_length=200)),
                ('tagged', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=999)),
                ('views', models.CharField(max_length=20)),
                ('wiki', models.BooleanField(null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
