# Generated by Django 3.2.4 on 2021-06-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_no', models.IntegerField(default=1)),
                ('page_size', models.IntegerField(default=15)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('order_by', models.CharField(choices=[('asc', 'asc'), ('desc', 'desc')], max_length=4)),
                ('min_date', models.DateField()),
                ('max_date', models.DateField()),
                ('sort_by', models.CharField(choices=[('activity', 'activity'), ('votes', 'votes'), ('creation', 'creation'), ('relevance', 'relevance')], max_length=10)),
                ('question', models.CharField(max_length=200)),
                ('is_accepted', models.BooleanField(null=True)),
                ('no_of_answers', models.IntegerField()),
                ('body', models.CharField(max_length=200)),
                ('is_closed', models.BooleanField(null=True)),
                ('is_migrated', models.BooleanField(null=True)),
                ('notice', models.BooleanField(null=True)),
                ('not_tagged', models.CharField(max_length=200)),
                ('tagged', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('user', models.IntegerField()),
                ('url', models.CharField(max_length=999)),
                ('views', models.IntegerField()),
                ('wiki', models.BooleanField(null=True)),
            ],
        ),
    ]
